#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_FILE="${CONFIG_FILE:-${ROOT_DIR}/train_1b/configs/dense_1b.env}"

if [[ ! -f "${CONFIG_FILE}" ]]; then
  echo "Config not found: ${CONFIG_FILE}" >&2
  exit 1
fi

# shellcheck source=/dev/null
source "${CONFIG_FILE}"

export WEIGHT_PREFIX RUN_GROUP WANDB_PROJECT
export HIDDEN_SIZE NUM_HIDDEN_LAYERS NUM_ATTENTION_HEADS NUM_KEY_VALUE_HEADS HEAD_DIM INTERMEDIATE_SIZE BRIDGE_LAYER
export TALKER_HIDDEN_SIZE NUM_TALKER_HIDDEN_LAYERS TALKER_NUM_ATTENTION_HEADS TALKER_NUM_KEY_VALUE_HEADS TALKER_HEAD_DIM TALKER_INTERMEDIATE_SIZE
export USE_MOE GRADIENT_CHECKPOINTING
export COMPILE_T2A COMPILE_A2A_PROJ COMPILE_A2A_FULL COMPILE_I2T_PROJ COMPILE_I2T_ALL COMPILE_A2A_FINAL COMPILE_I2T_FINAL
export DATA_T2A DATA_A2A DATA_I2T RANK_SHARDED_DATA
export SEQ_T2A SEQ_A2A SEQ_I2T
export BATCH_T2A BATCH_A2A_PROJ BATCH_A2A_FULL BATCH_I2T_PROJ BATCH_I2T_FULL ACCUMULATION_STEPS
export WARMUP_RATIO LOSS_NORM RVQ_LAYER_WEIGHTS AUDIO_STOP_WEIGHT VAL_INTERVAL VAL_DATA_T2A VAL_DATA_A2A VAL_DATA_I2T
export LR_T2A LR_A2A_PROJ LR_A2A_FULL LR_I2T_PROJ LR_I2T_ALL LR_A2A_FINAL LR_I2T_FINAL
export MUON_LR_T2A MUON_LR_A2A_PROJ MUON_LR_A2A_FULL MUON_LR_I2T_PROJ MUON_LR_I2T_ALL MUON_LR_A2A_FINAL MUON_LR_I2T_FINAL
export EPOCHS_T2A EPOCHS_A2A_PROJ EPOCHS_A2A_FULL EPOCHS_I2T_PROJ EPOCHS_I2T_ALL EPOCHS_A2A_FINAL EPOCHS_I2T_FINAL END_STAGE
export DDP_BROADCAST_BUFFERS FINITE_GUARD FINITE_GUARD_LOGITS_INTERVAL NUM_WORKERS LOG_INTERVAL SAVE_INTERVAL
export MAX_TRAIN_STEPS

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2}"
export NPROC_PER_NODE="${NPROC_PER_NODE:-3}"
export MASTER_PORT="${MASTER_PORT:-29561}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export TORCH_NCCL_ASYNC_ERROR_HANDLING="${TORCH_NCCL_ASYNC_ERROR_HANDLING:-1}"

STAGE1_FROM_WEIGHT="${STAGE1_FROM_WEIGHT:-llm}"
export STAGE1_FROM_WEIGHT

if [[ "${STAGE1_FROM_WEIGHT}" != "none" ]]; then
  PRETRAIN_PATH="${ROOT_DIR}/out/${STAGE1_FROM_WEIGHT}_${HIDDEN_SIZE}.pth"
  if [[ ! -f "${PRETRAIN_PATH}" && "${DRY_RUN:-0}" != "1" && "${ALLOW_SCRATCH_1B:-0}" != "1" ]]; then
    echo "Missing 1B text pretrain: ${PRETRAIN_PATH}" >&2
    echo "Set STAGE1_FROM_WEIGHT to an existing prefix, or set ALLOW_SCRATCH_1B=1 to train from scratch deliberately." >&2
    exit 2
  fi
fi

echo "1B config: ${CONFIG_FILE}"
echo "Stage1 pretrain prefix: ${STAGE1_FROM_WEIGHT}"
echo "Set DRY_RUN=1 for command expansion only."

exec bash "${ROOT_DIR}/scripts/run_full_train_muon_dense_3gpu.sh" "$@"
